/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Navbar: typeof import('./components/Navbar.vue')['default']
    OrderDisplay: typeof import('./components/OrderDisplay.vue')['default']
    PaymentOptions: typeof import('./components/PaymentOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShippingForm: typeof import('./components/ShippingForm.vue')['default']
    ShoppingCart: typeof import('./components/ShoppingCart.vue')['default']
  }
}
